### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by Raxana7** [17teen/7TEEN-MASS-DM-TOOL-V2#1]
![image](https://user-images.githubusercontent.com/48220802/103435857-d66e8400-4c25-11eb-90fe-1c9aed6de8b6.png)

**Comment by HaSeung101** [comment]
no

**Comment by 17teen** [comment]
It seems your Discord bot seems to not have Gateway Intents Privileges. 

Make sure to enable each intent by going to [Discord Dev App](https://discord.com/developers/applications), Select Bot > Bot and then scroll down till you see "Privileged Gateway Intents":

![example](https://camo.githubusercontent.com/3689f2f249a77983ae462a0f7354c784b8bbb41390b158bff1ab087c1a8d302d/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3738323231313932303431363733353235322f3738393831303835363436303431393039322f756e6b6e6f776e2e706e673f77696474683d31343039266865696768743d343030)
